version: '3.5'

services:
  db:
    # PostgreSQL 12 Database Server for the Django application in the development environment
    container_name: ms_django_db
    image: postgres:12
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./db/psql-init/db.sql:/docker-entrypoint-initdb.d/db.sql
      - postgres_data:/var/lib/postgresql/data/

  ms_django:
    # Django Application Server in the development environment
    container_name: ms_django
    tty: true
    build:
      context: ../
      dockerfile: ./docker/exampleDjangoProject/Dockerfile
      target: dev
    depends_on:
      - db
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_SETTINGS_MODULE=exampleDjangoProject.settings.development
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ../:/home/web/exampleDjangoProject

volumes:
  postgres_data:
